CC=gcc
SOURCE=args.c \
        avra.c \
        coff.c \
        device.c \
        directiv.c \
        expr.c \
        file.c \
        macro.c \
        map.c \
        mnemonic.c \
        parser.c \
        stdextra.c

all:
	$(CC) $(CDEFS) -o avra $(SOURCE)

